name: ci
run-name: Run CI

on:
  push:
    paths-ignore:
      - .editorconfig
      - .prettierignore
      - .prettier.cjs
      - CHANGELOG.md
      - LICENSE
      - README.md

jobs:
  ci-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node: [18, 20, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: npm Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

  ci-sonar:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 18.12.x

      - name: npm Install
        run: npm ci

      - name: Test with coverage
        run: npm run testWithCoverage

      - name: Get current version
        id: version
        run: |
          echo "value=$(npm pkg get version --workspaces=false | tr -d \")" >> "$GITHUB_OUTPUT"

      - name: Get current commit
        id: commit
        run: |
          echo "value=$(echo ${{ github.sha }} | sed 's/\(.\{7\}\).*/\1/')" >> "$GITHUB_OUTPUT"

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectVersion=${{ steps.version.outputs.value }}-${{ steps.commit.outputs.value }}
