name: Test/Build

on: [push]

jobs:
  build:
    name: Test/Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: install
        run: npm ci
      - name: test
        run: npm test
      - name: build
        run: npm run build
